---
- include: pkg-debian.yml
  when: ansible_os_family == "Debian"

- include: pkg-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create main Datadog agent configuration file
  template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog-agent

# DEPRECATED: Remove specific handling of the process check for next major release
- template: src=process.yaml.j2 dest=/etc/dd-agent/conf.d/process.yaml
  when: datadog_process_checks is defined
  notify: restart datadog

- debug: 'msg="[DEPRECATION NOTICE] Using `datadog_process_checks` is deprecated, use `process` under `datadog_checks` instead"'
  when: datadog_process_checks is defined

- service: name=datadog-agent state=started enabled=yes pattern=/opt/datadog-agent/bin/supervisord
  when: datadog_enabled

- service: name=datadog-agent state=stopped enabled=no pattern=/opt/datadog-agent/bin/supervisord
  when: not datadog_enabled

- name: Create a configuration file for each Datadog check
  template:
    src=checks.yaml.j2
    dest=/etc/dd-agent/conf.d/{{ item }}.yaml
  with_items: datadog_checks.keys()
  notify:
   - restart datadog-agent
